course_name = "自动控制实践 B"
course_code = "AUTO3002B"

notices = """自 22 级开始，本课程原有的 STM32 理论部分和基础实验、调速实验部分均被纳入大三上的拓展选修课《嵌入式系统》中。有关资料也已经转移，请移步查看。综合实验报告仍予保留。
注意，该课程为哈工大本部/深圳的考研复试课程。"""

[[lecturers]]
name = "董广忠"
  [[lecturers.reviews]]
  content = """授课风格：通过加入密度极高的无意义衬词以及含糊其辞的表述，成功达到让人听不懂的效果。答疑态度十分一般。
听课建议：不考勤。上课会提示重点，建议课后倍速听回放。课件在教师主页，不在 qq 群发放。"""
  author = { name = "Oliver Wu", link = "https://github.com/oliverwu515", date = "" }

[[lecturers]]
name = "王彬彬、刘瑞"
  [[lecturers.reviews]]
  content = "如遇到问题，建议自行 Google。"
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "控制系统设计"
book_author = "王广雄、何朕"
publisher = "清华大学出版社"
edition = ""
type = "textbook"
author = { name = "", link = "", date = "" }

online_resources = []

course = []

[[exam]]
content = """考试难度：较难
说明：注意老师给出的重点。同时对于理论部分的学习主要是一些固定的模型，注意公式推导和转换即可。实践部分听重点，过一遍 PPT 即可。"""
author = { name = "xander-2077", link = "https://github.com/xander-2077", date = "" }

[[exam]]
content = "主要是大背诵。"
author = { name = "Oliver Wu", link = "https://github.com/oliverwu515", date = "" }

[[exam]]
content = """从回忆卷子就可以看出，25 年的考试如往常一样的大背诵，我考试时不到一个小时手就写酸了。不过虽然老师上课的时候讲了很多次题目会完全重新出，但是实际上（除了那一道 Anti Windup 简答题）大部分题目还都是原题，甚至最后一道设计大题完完全全没有变化，因此只要把往年题都做做好，考试的时候就不会有太大问题。

虽然听大家多会抱怨这门课，我个人觉得这门课在逻辑性和知识点密度上还是很不错的（相比自控实践 A 好了不是一点半点），大部分问题估计就是学生和老师之间沟通不够及时，很多问题没法有效解决，因此我写了往年题目的详解并放在 exams 文件夹下，供大家参考，大家做题时可以多和同学们交流，大部分情况都只能将大多数人认同的答案作为参考。"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2025-06-01" }

lab = []

advice = []

schedule = []

related_links = []

misc = []